type = "service_account"
project_id = "aqueous-freedom-428915-e2"
private_key_id = "d96d099bb65e2dfb32a6f8fac7a00351e3ad67d9"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCijU2qF4yGcXUD
iulKPKfgPbo8RXEw4gsApiVOsdDnEC1+NWSynAqgCrE1MOgMzTz968Xbq+6inLhU
4g/34m7S9hY8fG0yWMdd8LVMMZCJH3qsdt19TlkswkFI1c3O+Iw8pikhZ4SM+52Z
Ahnbwejb7wZ8dOazpVu3ujiSXHYOY9UAkgBkNAKRjHE61KJr4LkCHPBuZHe8um97
1rNRtMb3FQK0KgT1NSEhRjksChTlbFQjehSYur6MjhgutRju39w9IGrUuMqcC/8i
5yaNJ9w158hPp8Z8yqtiUjo71QDLbktXsX3KIql1ium+T53wd0ffUb+rHa0vsgg0
+dbFSk8jAgMBAAECggEAOHbXDIeDk8vjdqiRIu1w7w7iGz+P8wgCBGayPOS9iRXw
h4+qe/SCKFeueKiVYqUEU7vLjePqT+gai7m/DD9Geddrn/UkxUFbd4E+qMnqyAb8
SN49T+KgTVDo9pD2Hbfulr6tOOJJg+N/OgAl1VVFOuiLmz3MSYjeFDMGpaiihZqQ
KLosMioBgrqzK4JOjfu7A0MLYz5YE93E/oIpQqRZIMb8/A5r0T/JPAZPwxwGE+NT
J88YWSXg6UDyLBnrQm9ZglxmXgj6rKOrliV4zQW0ezCdKZU3s+iGJO1F9B4EkgSC
zS+QIZOWrlSmGJ9n+KY/anuFB+fn5sVVV/a5D8HD2QKBgQDV3ppEisWUBOIaGl5z
/3OkHNzVYQLgVP2PoexLUdctWjekLogVZelH8hcI0fbq8xWOa2iLWaSqGu5gtj11
y5pTp1SrY7WgGYMZv1hZCl9qof7eSPgDnAUiEUdifk4FxHKEuDtzL7Fwsb3NuCGD
W/G5xNtsqQEtL1Y3cZ0uOpsz1QKBgQDCksQS1uYenABsq6aoxP26+liUV1hD84Tc
7KBKdc+izHzGRVxlZF22NqUkwNCLXa6wF72wbCTMoTF5USzUSYKYqHERieq40uma
dptUptdQyZ3QWc7LjtjJrgZ7G69McW5Pxj39uc8EIzmzasCw+YCYXLWNDUdV7Mzl
steAiWSLFwKBgBYR6aOHGoqC0n5VGEgqJVnbLKLMZwqVWrE2yXagVG82ryU/NAXZ
RXCKN/xOBogKW8Adr2Up9AclzlGmnMMKJrvZObCSEo0Z9OB0UX6mxl/vpah0qTte
H117oP02AYEw24x8oo3pbwstHGQdS0AN/ezotqgI7Lkn+GKyU8EQhTGdAoGBAIxU
1AuOaKwc8YVvC6VfZmyLkIV0tZlUsjewhi8N5zJQb5GEhw4tpBT+Nn9afU52w74H
cW0joirf+1G3RTDaz9EQc3Ql119z5r3b203jgxmmQCb8DtTrctmKpOv3XKgyi1AH
97/eWjtuuHf5f35khOXev6Y6tH95aZIlOZ5f+V8DAoGBALXrCOyy9RyAueVj2nTQ
IrEZlsrSVMsTjv2/o5I5EEZIK515OLkKiqwdZgw2XemyxaiXIHpk4DNH/gvPR8oH
ShuQW7YpFIKlbbcNpig7RZxZNJ9fu7vQbKTwqNNJ4DZiIkz94JrHlZCakiChb4tM
lOt2rPZnYASam3xGCLFsYHj0
-----END PRIVATE KEY-----
"""
client_email = "nist-ai-rmf-maturitymodelfeedb@aqueous-freedom-428915-e2.iam.gserviceaccount.com"
client_id = "112026427659472323238"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/nist-ai-rmf-maturitymodelfeedb%40aqueous-freedom-428915-e2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
